import { StyleSheet, Platform } from 'react-native';
import { Theme } from '../constants/Theme';
import { ms } from '../utils/scaling';

export const styles = StyleSheet.create({
  center: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center', 
    backgroundColor: Theme.colors.background 
  },
  container: {
    flex: 1,
    backgroundColor: Theme.colors.background,
    paddingTop: ms(30)
  },
  header: {
    paddingHorizontal: Theme.spacing.lg,
    paddingTop: Platform.OS === 'ios' ? ms(20) : ms(10),
    paddingBottom: Theme.spacing.lg,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: Theme.colors.surface,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoPlaceholder: {
    width: ms(38),
    height: ms(38),
    borderRadius: ms(19),
    backgroundColor: Theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: Theme.spacing.md,
  },
  headerBrand: {
    fontSize: Theme.typography.fontSizes.md,
    fontWeight: Theme.typography.fontWeight.bold,
    color: Theme.colors.primary,
  },
  offlineToggle: {
    width: ms(40),
    height: ms(40),
    borderRadius: Theme.borderRadius.full,
    backgroundColor: Theme.colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  offlineToggleActive: {
    backgroundColor: '#FEE2E2',
    borderWidth: 1,
    borderColor: Theme.colors.danger,
  },
  mainContent: {
    flex: 1,
    alignItems: 'center',
    paddingHorizontal: Theme.spacing.lg,
  },
  titleContainer: {
    alignItems: 'center',
    marginBottom: Theme.spacing.lg,
  },
  pageTitle: {
    fontSize: ms(29),
    fontWeight: Theme.typography.fontWeight.heavy,
    color: Theme.colors.text.primary,
    lineHeight: ms(36),
    marginBottom: Theme.spacing.xs,
  },
  pageSubtitle: {
    fontSize: Theme.typography.fontSizes.md,
    color: Theme.colors.text.secondary,
  },
  scannerWrapper: {
    height: ms(260),
    width: ms(260),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: Theme.spacing.lg,
  },
  pulseCircle: {
    position: 'absolute',
    width: ms(200),
    height: ms(200),
    borderRadius: ms(100),
    backgroundColor: 'rgba(0, 86, 210, 0.1)',
  },
  solidCircle: {
    width: ms(200),
    height: ms(200),
    borderRadius: ms(100),
    backgroundColor: Theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadows.medium,
    shadowColor: Theme.colors.primary,
  },
  instructionCard: {
    width: '100%',
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.borderRadius.xxl,
    padding: Theme.spacing.xl,
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
    ...Theme.shadows.light,
  },
  instructionText: {
    fontSize: Theme.typography.fontSizes.lg,
    fontWeight: Theme.typography.fontWeight.bold,
    color: Theme.colors.text.primary,
    textAlign: 'center',
    marginVertical: Theme.spacing.md,
    lineHeight: ms(30),
  },
  listeningBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.border,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.sm,
    borderRadius: Theme.borderRadius.xl,
  },
  listeningDot: {
    width: ms(8),
    height: ms(8),
    borderRadius: ms(4),
    backgroundColor: Theme.colors.success,
    marginRight: Theme.spacing.sm,
  },
  listeningText: {
    fontSize: Theme.typography.fontSizes.xs,
    fontWeight: Theme.typography.fontWeight.heavy,
    color: '#065f46',
    letterSpacing: 1,
  },
  registrationCard: {
    width: '100%',
    backgroundColor: Theme.colors.surface,
    borderRadius: Theme.borderRadius.xxl,
    padding: Theme.spacing.xl,
    ...Theme.shadows.medium,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  tagInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Theme.colors.background,
    padding: Theme.spacing.md,
    borderRadius: Theme.borderRadius.md,
    marginBottom: Theme.spacing.lg,
  },
  tagCode: {
    fontSize: Theme.typography.fontSizes.sm,
    fontWeight: Theme.typography.fontWeight.bold,
    color: Theme.colors.primary,
    marginLeft: Theme.spacing.sm,
  },
  formInput: {
    backgroundColor: Theme.colors.background,
    borderWidth: 2,
    borderColor: Theme.colors.border,
    borderRadius: Theme.borderRadius.xl,
    padding: Theme.spacing.lg,
    fontSize: ms(17),
    color: Theme.colors.text.primary,
    fontWeight: Theme.typography.fontWeight.bold,
    marginBottom: Theme.spacing.lg,
  },
  resultCard: {
    width: '100%',
    backgroundColor: Theme.colors.surface,
    borderRadius: ms(40),
    padding: ms(24),
    alignItems: 'center',
    ...Theme.shadows.light,
  },
  successIconOuter: {
    width: ms(100),
    height: ms(100),
    borderRadius: ms(50),
    backgroundColor: Theme.colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: ms(30),
  },
  successIconInner: {
    width: ms(70),
    height: ms(70),
    borderRadius: ms(35),
    backgroundColor: Theme.colors.success,
    justifyContent: 'center',
    alignItems: 'center',
  },
  resultTitleContainer: {
    alignItems: 'center',
    marginBottom: ms(24),
  },
  resultMainTitle: {
    fontSize: ms(28),
    fontWeight: Theme.typography.fontWeight.heavy,
    color: Theme.colors.text.primary,
    textAlign: 'center',
    marginBottom: ms(10),
  },
  resultSubtitle: {
    fontSize: ms(17),
    color: Theme.colors.text.secondary,
    textAlign: 'center',
    paddingHorizontal: ms(20),
    lineHeight: ms(24),
  },
  primaryButton: {
    width: '100%',
    height: ms(56),
    backgroundColor: Theme.colors.primary,
    borderRadius: Theme.borderRadius.lg,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    ...Theme.shadows.medium,
    shadowColor: Theme.colors.primary,
  },
  primaryButtonText: {
    fontSize: ms(18),
    fontWeight: Theme.typography.fontWeight.heavy,
    color: Theme.colors.text.light,
  },
  dangerButton: {
    width: '100%',
    height: ms(60),
    backgroundColor: '#fee2e2',
    borderRadius: ms(30),
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: ms(12),
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  dangerButtonText: {
    fontSize: ms(18),
    fontWeight: Theme.typography.fontWeight.heavy,
    color: Theme.colors.danger,
  },
  offlineBanner: {
    position: 'absolute',
    top: ms(100),
    alignSelf: 'center',
    backgroundColor: Theme.colors.warning,
    paddingHorizontal: Theme.spacing.md,
    paddingVertical: Theme.spacing.xs,
    borderRadius: Theme.borderRadius.md,
  },
  offlineBannerText: {
    color: Theme.colors.text.light,
    fontSize: ms(10),
    fontWeight: Theme.typography.fontWeight.bold,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: Theme.spacing.md,
    backgroundColor: Theme.colors.surface,
    padding: Theme.spacing.md,
    borderRadius: Theme.borderRadius.xl,
    borderWidth: 1,
    borderColor: Theme.colors.border,
  },
  avatarContainer: {
    width: ms(48),
    height: ms(48),
    borderRadius: ms(24),
    backgroundColor: Theme.colors.background,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: Theme.colors.surface,
    ...Theme.shadows.light,
  },
  statusBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: ms(20),
    height: ms(20),
    borderRadius: ms(10),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: Theme.colors.surface
  },
  infoTextMain: {
    fontSize: ms(16),
    fontWeight: Theme.typography.fontWeight.heavy,
    color: Theme.colors.text.primary,
  },
  infoTextSub: {
    fontSize: ms(12),
    fontWeight: Theme.typography.fontWeight.bold,
    marginTop: ms(2),
  },
  statusTextIn: {
    color: Theme.colors.success,
  },
  statusTextOut: {
    color: Theme.colors.warning,
  },
  actionButtonGroup: {
    gap: Theme.spacing.md,
    width: '100%',
    marginTop: Theme.spacing.lg,
  },
  historyListCard: {
    marginTop: ms(10),
    backgroundColor: Theme.colors.surface,
    alignItems: 'stretch',
    padding: ms(15),
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Theme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Theme.colors.border,
    paddingBottom: Theme.spacing.sm
  },
  cardHeaderText: {
    fontSize: ms(15),
    fontWeight: Theme.typography.fontWeight.heavy,
    color: Theme.colors.text.primary
  },
});
